apiVersion: v1
kind: Pod
metadata:
  name: centos5
spec:
  nodeName: sugao-k8s-worker3
  restartPolicy: OnFailure
  containers:
    - name: centos5
      image: centos:7
      command:
        - "/sbin/init"
