apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r1-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r1-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r1-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r1-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: r1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r1-net1"},
      {"name": "r1-net2"}
    ]'
spec: 
  nodeName: sugao-k8s-v2-w1
  containers:
  - name: frr
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
      postStart:
        exec:
          command:
            - sh
            - -c
            - |
              ip link set eth0 down
              ip addr add 192.168.0.1/24 dev net1
              ip addr add 192.168.1.1/24 dev net2
              vtysh -c "configure terminal" -c "ip route 192.168.3.0/24 192.168.2.2"