apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r1-eth1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r1-br1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r1-eth2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r1-br2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: frr3
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r1-eth1"},
      {"name": "r1-eth2"}
    ]'
spec: 
  containers:
  - name: frr3
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true