apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r1-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r1-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r1-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r1-net2",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: h1-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "h1-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: h2-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "h2-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: r1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r1-net1"},
      {"name": "r1-net2"}
    ]'
spec: 
  nodeName: sugao-k8s-v2-w1
  containers:
  - name: frr
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
      postStart:
        exec:
          command:
            - sh
            - -c
            - |
              ip link set eth0 down
              ip addr add 192.168.0.1/24 dev net1
              ip addr add 192.168.1.1/24 dev net2
---
apiVersion: v1
kind: Pod
metadata:
  name: h1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "h1-net1"}
    ]'
  labels:
    app: ubuntu
spec:
  nodeName: sugao-k8s-v2-w1
  containers:
    - name: ubuntu-container
      image: sugaott/sugaott-ubuntu-focal:1.4
      securityContext:
        privileged: true
      command: ["bash", "-c", "sleep infinity"]
      ports:
        - containerPort: 5201
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - |
                ip link set eth0 down
                ip addr add 192.168.0.2/24 dev net1
                ip route add default via 192.168.0.1
---
apiVersion: v1
kind: Pod
metadata:
  name: h2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "h2-net1"}
    ]'
  labels:
    app: ubuntu
spec:
  nodeName: sugao-k8s-v2-w1
  containers:
    - name: ubuntu-container
      image: sugaott/sugaott-ubuntu-focal:1.4
      securityContext:
        privileged: true
      command: ["bash", "-c", "sleep infinity"]
      ports:
        - containerPort: 5201
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - |
                ip link set eth0 down
                ip addr add 192.168.1.2/24 dev net1
                ip route add default via 192.168.1.1
