apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r1-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r1-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r1-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r1-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: r1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r1-net1"},
      {"name": "r1-net2"}
    ]'
spec: 
  nodeName: sugao-k8s-v2-w1
  containers:
  - name: frr
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
      postStart:
        exec:
          command:
            - sh
            - -c
            - |
              ip link set eth0 down
              ip addr add 192.168.0.1/24 dev net1
              ip addr add 192.168.1.1/24 dev net2
              vtysh -c "configure terminal" -c "ip route 192.168.2.0/24 192.168.1.2"
              vtysh -c "configure terminal" -c "ip route 192.168.3.0/24 192.168.1.2"
              vtysh -c "configure terminal" -c "ip route 192.168.4.0/24 192.168.1.2"
              vtysh -c "configure terminal" -c "ip route 192.168.5.0/24 192.168.1.2"
              vtysh -c "configure terminal" -c "ip route 192.168.6.0/24 192.168.1.2"
              vtysh -c "configure terminal" -c "ip route 192.168.7.0/24 192.168.1.2"
              vtysh -c "configure terminal" -c "ip route 192.168.8.0/24 192.168.1.2"
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r2-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r2-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r2-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r2-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: r2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r2-net1"},
      {"name": "r2-net2"}
    ]'
spec: 
  nodeName: sugao-k8s-v2-w1
  containers:
  - name: frr
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
      postStart:
        exec:
          command:
            - sh
            - -c
            - |
              ip link set eth0 down
              ip addr add 192.168.1.2/24 dev net1
              ip addr add 192.168.2.1/24 dev net2
              vtysh -c "configure terminal" -c "ip route 192.168.0.0/24 192.168.1.1"
              vtysh -c "configure terminal" -c "ip route 192.168.3.0/24 192.168.2.2"
              vtysh -c "configure terminal" -c "ip route 192.168.4.0/24 192.168.2.2"
              vtysh -c "configure terminal" -c "ip route 192.168.5.0/24 192.168.2.2"
              vtysh -c "configure terminal" -c "ip route 192.168.6.0/24 192.168.2.2"
              vtysh -c "configure terminal" -c "ip route 192.168.7.0/24 192.168.2.2"
              vtysh -c "configure terminal" -c "ip route 192.168.8.0/24 192.168.2.2"
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r3-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r3-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r3-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r3-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: r3
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r3-net1"},
      {"name": "r3-net2"}
    ]'
spec: 
  nodeName: sugao-k8s-v2-w1
  containers:
  - name: frr
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
      postStart:
        exec:
          command:
            - sh
            - -c
            - |
              ip link set eth0 down
              ip addr add 192.168.2.2/24 dev net1
              ip addr add 192.168.3.1/24 dev net2
              vtysh -c "configure terminal" -c "ip route 192.168.0.0/24 192.168.2.1"
              vtysh -c "configure terminal" -c "ip route 192.168.1.0/24 192.168.2.1"
              vtysh -c "configure terminal" -c "ip route 192.168.4.0/24 192.168.3.2"
              vtysh -c "configure terminal" -c "ip route 192.168.5.0/24 192.168.3.2"
              vtysh -c "configure terminal" -c "ip route 192.168.6.0/24 192.168.3.2"
              vtysh -c "configure terminal" -c "ip route 192.168.7.0/24 192.168.3.2"
              vtysh -c "configure terminal" -c "ip route 192.168.8.0/24 192.168.3.2"
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r4-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r4-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r4-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r4-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: r4
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r4-net1"},
      {"name": "r4-net2"}
    ]'
spec: 
  nodeName: sugao-k8s-v2-w1
  containers:
  - name: frr
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
      postStart:
        exec:
          command:
            - sh
            - -c
            - |
              ip link set eth0 down
              ip addr add 192.168.3.2/24 dev net1
              ip addr add 192.168.4.1/24 dev net2
              vtysh -c "configure terminal" -c "ip route 192.168.0.0/24 192.168.3.1"
              vtysh -c "configure terminal" -c "ip route 192.168.1.0/24 192.168.3.1"
              vtysh -c "configure terminal" -c "ip route 192.168.2.0/24 192.168.3.1"
              vtysh -c "configure terminal" -c "ip route 192.168.5.0/24 192.168.4.2"
              vtysh -c "configure terminal" -c "ip route 192.168.6.0/24 192.168.4.2"
              vtysh -c "configure terminal" -c "ip route 192.168.7.0/24 192.168.4.2"
              vtysh -c "configure terminal" -c "ip route 192.168.8.0/24 192.168.4.2"
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r5-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r5-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r5-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r5-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: r5
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r5-net1"},
      {"name": "r5-net2"}
    ]'
spec: 
  nodeName: sugao-k8s-v2-w2
  containers:
  - name: frr
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
      postStart:
        exec:
          command:
            - sh
            - -c
            - |
              ip link set eth0 down
              ip addr add 192.168.4.2/24 dev net1
              ip addr add 192.168.5.1/24 dev net2
              vtysh -c "configure terminal" -c "ip route 192.168.0.0/24 192.168.4.1"
              vtysh -c "configure terminal" -c "ip route 192.168.1.0/24 192.168.4.1"
              vtysh -c "configure terminal" -c "ip route 192.168.2.0/24 192.168.4.1"
              vtysh -c "configure terminal" -c "ip route 192.168.3.0/24 192.168.4.1"
              vtysh -c "configure terminal" -c "ip route 192.168.6.0/24 192.168.5.2"
              vtysh -c "configure terminal" -c "ip route 192.168.7.0/24 192.168.5.2"
              vtysh -c "configure terminal" -c "ip route 192.168.8.0/24 192.168.5.2"
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r6-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r6-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r6-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r6-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: r6
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r6-net1"},
      {"name": "r6-net2"}
    ]'
spec: 
  nodeName: sugao-k8s-v2-w2
  containers:
  - name: frr
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
      postStart:
        exec:
          command:
            - sh
            - -c
            - |
              ip link set eth0 down
              ip addr add 192.168.5.2/24 dev net1
              ip addr add 192.168.6.1/24 dev net2
              vtysh -c "configure terminal" -c "ip route 192.168.0.0/24 192.168.5.1"
              vtysh -c "configure terminal" -c "ip route 192.168.1.0/24 192.168.5.1"
              vtysh -c "configure terminal" -c "ip route 192.168.2.0/24 192.168.5.1"
              vtysh -c "configure terminal" -c "ip route 192.168.3.0/24 192.168.5.1"
              vtysh -c "configure terminal" -c "ip route 192.168.4.0/24 192.168.5.1"
              vtysh -c "configure terminal" -c "ip route 192.168.7.0/24 192.168.6.2"
              vtysh -c "configure terminal" -c "ip route 192.168.8.0/24 192.168.6.2"
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r7-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r7-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r7-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r7-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: r7
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r7-net1"},
      {"name": "r7-net2"}
    ]'
spec: 
  nodeName: sugao-k8s-v2-w2
  containers:
  - name: frr
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
      postStart:
        exec:
          command:
            - sh
            - -c
            - |
              ip link set eth0 down
              ip addr add 192.168.6.2/24 dev net1
              ip addr add 192.168.7.1/24 dev net2
              vtysh -c "configure terminal" -c "ip route 192.168.0.0/24 192.168.6.1"
              vtysh -c "configure terminal" -c "ip route 192.168.1.0/24 192.168.6.1"
              vtysh -c "configure terminal" -c "ip route 192.168.2.0/24 192.168.6.1"
              vtysh -c "configure terminal" -c "ip route 192.168.3.0/24 192.168.6.1"
              vtysh -c "configure terminal" -c "ip route 192.168.4.0/24 192.168.6.1"
              vtysh -c "configure terminal" -c "ip route 192.168.5.0/24 192.168.6.1"
              vtysh -c "configure terminal" -c "ip route 192.168.8.0/24 192.168.7.2"
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r8-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r8-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r8-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r8-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: r8
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r8-net1"},
      {"name": "r8-net2"}
    ]'
spec: 
  nodeName: sugao-k8s-v2-w2
  containers:
  - name: frr
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
      postStart:
        exec:
          command:
            - sh
            - -c
            - |
              ip link set eth0 down
              ip addr add 192.168.7.2/24 dev net1
              ip addr add 192.168.8.1/24 dev net2
              vtysh -c "configure terminal" -c "ip route 192.168.0.0/24 192.168.7.1"
              vtysh -c "configure terminal" -c "ip route 192.168.1.0/24 192.168.7.1"
              vtysh -c "configure terminal" -c "ip route 192.168.2.0/24 192.168.7.1"
              vtysh -c "configure terminal" -c "ip route 192.168.3.0/24 192.168.7.1"
              vtysh -c "configure terminal" -c "ip route 192.168.4.0/24 192.168.7.1"
              vtysh -c "configure terminal" -c "ip route 192.168.5.0/24 192.168.7.1"
              vtysh -c "configure terminal" -c "ip route 192.168.6.0/24 192.168.7.1"
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: h1-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "h1-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: h1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "h1-net1"}
    ]'
  labels:
    app: ubuntu
spec:
  nodeName: sugao-k8s-v2-w1
  containers:
    - name: ubuntu-container
      image: sugaott/sugaott-ubuntu-focal:1.4
      securityContext:
        privileged: true
      command: ["bash", "-c", "sleep infinity"]
      ports:
        - containerPort: 5201
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - |
                ip link set eth0 down
                ip addr add 192.168.0.2/24 dev net1
                ip route add default via 192.168.0.1
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: h2-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "h2-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: h2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "h2-net1"}
    ]'
  labels:
    app: ubuntu
spec:
  nodeName: sugao-k8s-v2-w2
  containers:
    - name: ubuntu-container
      image: sugaott/sugaott-ubuntu-focal:1.4
      securityContext:
        privileged: true
      command: ["bash", "-c", "sleep infinity"]
      ports:
        - containerPort: 5201
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - |
                ip link set eth0 down
                ip addr add 192.168.8.2/24 dev net1
                ip route add default via 192.168.8.1
