apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: s1-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "s1-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: s1-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "s1-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: ovs
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "s1-net1"},
      {"name": "s1-net2"}
    ]'
spec:
  containers:
    - name: ovs
      image: openshift/openvswitch:v3.9.0
      command:
        - /sbin/init
      securityContext:
        privileged: true
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - "/usr/share/openvswitch/scripts/ovs-ctl start;ovs-vsctl add-br Switch0;ovs-vsctl add-port Switch0 net1;ovs-vsctl add-port Switch0 net2;ip link set eth0 down; ip link set net1 down"
