apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-b724143c
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "b724143c",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "eca7f7be",
            "target-pod-nic": "net1",
            "self-tunnel-id": "3",
            "target-tunnel-id": "2",
            "session-id": "1"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: b724143c-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "b724143c-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: b724143c
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "b724143c-net1"},
      {"name": "connect-b724143c"}
    ]'
spec: 
  containers:
  - name: b724143c
    image: frrouting/frr:v8.1.0
    command:
    - /sbin/init
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-eca7f7be
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "eca7f7be",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "b724143c",
            "target-pod-nic": "net1",
            "self-tunnel-id": "2",
            "target-tunnel-id": "3",
            "session-id": "1"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: eca7f7be-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "eca7f7be-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: eca7f7be
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "eca7f7be-net1"},
      {"name": "connect-eca7f7be"}
    ]'
spec: 
  containers:
  - name: eca7f7be
    image: frrouting/frr:v8.1.0
    command:
    - /sbin/init
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"