apiVersion: v1
kind: Pod
metadata:
  name: centos1
spec:
  hostNetwork: true
  nodeName: sugao-k8s-worker4
  restartPolicy: OnFailure
  containers:
    - name: centos1
      image: centos:7
      command:
        - "/sbin/init"