apiVersion: v1
kind: Pod
metadata:
  name: h3-t
  labels:
    app: ubuntu
spec:
  nodeName: sugao-k8s-worker3-n
  containers:
    - name: ubuntu-container
      image: sugaott/sugaott-ubuntu-focal:1.4
      command: ["bash", "-c", "sleep infinity"]
      ports:
        - containerPort: 5201
